### ISSUE TITLE
🚘 v1.0.0 Roadmap

### ISSUE THREAD

**Issue by jlalmes** [jlalmes/trpc-openapi#91]
### 🏠 House keeping

- [x] Write `v0` -> `v1` migration guide. (currently maintained here https://github.com/jlalmes/trpc-openapi/pull/143)

### 🚀 Definite

- [x] Support tRPC `v10`. (https://github.com/jlalmes/trpc-openapi/issues/73)
- [x] Remove response wrapper (https://github.com/jlalmes/trpc-openapi/pull/144)
- [x] Add CORS setup to examples. (https://github.com/jlalmes/trpc-openapi/pull/122)
- [x] Deprecate `meta.tag` (use `meta.tags` instead). (https://github.com/jlalmes/trpc-openapi/pull/92)
- [x] Default to `enabled: true` when `meta.openapi` is defined. (https://github.com/jlalmes/trpc-openapi/issues/68)
- [x] Fix YAML file `$refs`. (https://github.com/jlalmes/trpc-openapi/issues/37)
- [x] Allow `method: 'DELETE'` in `mutation` procedures. (https://github.com/jlalmes/trpc-openapi/pull/123)
- [x] Add `meta.headers`. (https://github.com/jlalmes/trpc-openapi/issues/113)
- [x] Support `z.refine()`. (https://github.com/jlalmes/trpc-openapi/pull/102)
- [x] Performance improvements. (https://github.com/jlalmes/trpc-openapi/pull/125)
- [x] #156

### 🤔 Maybe
- [ ] Support `z.number()` query input. (https://github.com/jlalmes/trpc-openapi/issues/44)
- [ ] Support `z.boolean()` query input. (https://github.com/jlalmes/trpc-openapi/issues/44)
- [ ] Support `z.date()` query input. (https://github.com/jlalmes/trpc-openapi/issues/44)
- [ ] Support `z.array()` query inputs. (https://github.com/modtree/modtree/pull/358#discussion_r929558840)
- [ ] Add model schemas to OpenAPI document. (https://github.com/jlalmes/trpc-openapi/issues/157)
- [ ] Add `Fastify` adapter. (https://github.com/jlalmes/trpc-openapi/issues/87)
- [x] Add `Lambda` adapter. (https://github.com/jlalmes/trpc-openapi/issues/115)
- [ ] Add `meta.examples`.
- [ ] Add `override` object to `OpenApiMeta` and `GenerateOpenApiDocumentOptions`.

### 🏋️‍♀️ Stretch
- [ ] Support non-`z.object()` input.
  - Input is mandated as `z.object()` if using `pathParameters`.
  - Query input should be `?input=`.
- [ ] Remove `output` schema requirement. (https://github.com/jlalmes/trpc-openapi/issues/61#issuecomment-1180611408)
- [ ] Remove `zod` validator requirement.

**Comment by jlalmes** [comment]
Merged & published under `trpc-openapi@1`
